In [1]:
from ekonlpy.sentiment import MPCK
from bs4 import BeautifulSoup
from pandas import Series
import numpy as np
import os
import pandas as pd
from nltk.corpus import stopwords
from pandas import DataFrame

In [2]:
df = pd.read_csv('../data/bok_data.csv')

In [3]:
df

,date,title,content
0,2011-03-10,제7차 금통위 의사록 (6),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
1,2011-03-24,제8차 금통위 의사록 (4),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
2,2011-04-12,제9차 금통위 의사록 (5),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
3,2011-05-13,제13차 금통위 의사록 (6),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
4,2011-06-10,제15차 금통위 의사록 (5),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
...,...,...,...
225,2022-08-25,금융통화위원회 의사록(2022년도 제16차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
226,2022-09-08,금융통화위원회 의사록(2022년도 제17차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
227,2022-09-22,금융통화위원회 의사록(2022년도 제18차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
228,2022-10-12,금융통화위원회 의사록(2022년도 제19차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...
229,2022-10-27,금융통화위원회 의사록(2022년도 제20차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...

In [123]:
del df['Unnamed: 0']

In [124]:
del df['채권분석pdf링크']

In [125]:
df.rename(columns={'날짜':'date', '내용':'content'}, inplace= True)

In [126]:
df

            date                                            content
0     2012.01.02  Fixed Income Report2012.01.02유럽위기와 인플레 우려에 따른 ...
1     2012.01.03  Economic Comment2012. 1. 3Macro Comment: 유로화 저...
2     2012.01.03  2012년 1월 3일 (화)▶ 양호한 미국 지표 흐름 속에 점증하는 우려감잠시 소강...
3     2012.01.03  2012.01.03Macro VisionWeekly Focus국제유가, 추가 상승 ...
4     2012.01.04  Strategy Comment바닥을 통과하는 상품시장?2012. 01. 04− 상품...
...          ...                                                ...
5568  2022.11.16  2022년 11월 16일 I Global Asset ResearchGlobal Ma...
5569  2022.11.16  글로벌 경제 전망체크메이트(Checkmate)
Summary각자 품은 문제가 달라진...
5570  2022.11.16  2022년 11월 16일매크로분석Macro Review10월 중국 실물지표: 경기 ...
5571  2022.11.16  2022/11/16[Economist] 박상현 2122-9196 shpark@hi-...
5572  2022.11.17  ᆋ㦃⭠ KRMXQJNLP#\XDQWDNRUHDFRP⅗ᬸ...

[5573 rows x 2 columns]

In [127]:
df.to_csv('../data/bond_data.csv')

In [128]:
df

            date                                            content
0     2012.01.02  Fixed Income Report2012.01.02유럽위기와 인플레 우려에 따른 ...
1     2012.01.03  Economic Comment2012. 1. 3Macro Comment: 유로화 저...
2     2012.01.03  2012년 1월 3일 (화)▶ 양호한 미국 지표 흐름 속에 점증하는 우려감잠시 소강...
3     2012.01.03  2012.01.03Macro VisionWeekly Focus국제유가, 추가 상승 ...
4     2012.01.04  Strategy Comment바닥을 통과하는 상품시장?2012. 01. 04− 상품...
...          ...                                                ...
5568  2022.11.16  2022년 11월 16일 I Global Asset ResearchGlobal Ma...
5569  2022.11.16  글로벌 경제 전망체크메이트(Checkmate)
Summary각자 품은 문제가 달라진...
5570  2022.11.16  2022년 11월 16일매크로분석Macro Review10월 중국 실물지표: 경기 ...
5571  2022.11.16  2022/11/16[Economist] 박상현 2122-9196 shpark@hi-...
5572  2022.11.17  ᆋ㦃⭠ KRMXQJNLP#\XDQWDNRUHDFRP⅗ᬸ...

[5573 rows x 2 columns]

In [4]:
def n_gram_tokenize(csv_loc):
  train_data = pd.read_csv(csv_loc)
  df_bond = pd.DataFrame({'date','content'})
  mpck = MPCK()

  stop_words = ['NR','VV','VA',
                'VX', 'VCP', 'VCN', 'MM', 'MAJ', 'IC',
                'JKS', 'JKC', 'JKG', 'JKO', 'JKB',
                'JKV', 'JKQ', 'JX', 'JC', 'EP', 'EF',
                'EC', 'ETN', 'ETM', 'XPN', 'XSN',
                'XSV', 'XSA', 'XR', 'SF', 'SE',
                'SSO', 'SSC', 'SC', 'SY', 'SL',
                'SH', 'SN']
  bond_tokens_list = []
  final_bond = []
  ngram_result= {}
  bond_text = train_data['content']


  print(type(bond_text))
  print(len(bond_text))
  for i in range(len(bond_text)):
    bond_token = mpck.tokenize(str(bond_text.loc[i]))
    bond_tokens_list.append(bond_token)
    bond_stopword_result = []
    #print(bond_token)

    for bond in bond_tokens_list[i]:
        #print(bond)
        bond_ = bond.split('/')[1]
        # print(bond_)
        for stop in stop_words:
            if bond_ != stop:
                if stop == stop_words[-1]:
                    bond_stopword_result.append(bond)
                else:
                    pass 
            else:
                break


    final_bond.append((bond_stopword_result))
                # dict = {len(bond_text.loc[i]):fianl_bond[i]}
  for j in range (len(final_bond)):
    ngram_result.update({j:mpck.ngramize(final_bond[j])})

  df_ngram = pd.Series(ngram_result)
  # print(df_ngram)
  print(df_bond)
  result_bond = pd.concat([train_data, df_ngram],axis=1)
  result_bond.rename(columns = {0:'ngram'},inplace=True)

  result_bond.to_csv('../data/bok_ngram11111.csv')

  return print('csv파일 생성 완료!')

In [5]:
# 최종파일 생성
n_gram_tokenize('../data/all_data_merge_ngram.csv')

<class 'pandas.core.series.Series'>
260
         0
0     date
1  content
csv파일 생성 완료!

In [6]:
df = pd.read_csv('../data/bok_ngram11111.csv')

In [7]:
df

,Unnamed: 0,date,title,content,ngram
0,0,2009-11-12,제24차 금통위 의사록 (6),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['금리/NNG;인상/NNG;내외/NNG;금리갭/NNG;확대/NNG', '지표/NN..."
1,1,2009-11-26,제25차 금통위 의사록 (6),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,['물가/NNG;안정/NNG']
2,2,2009-12-10,제26차 금통위 의사록 (2),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['자산/NNG;가격/NNG;상승/NNG;인플레이션/NNG;압력/NNG', '원유/..."
3,3,2009-12-24,제27차 금통위 의사록 (1),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,[]
4,4,2010-01-07,제1차 금통위 의사록 (8),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,[]
...,...,...,...,...,...
255,255,2022-08-25,금융통화위원회 의사록(2022년도 제16차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '국제/..."
256,256,2022-09-08,금융통화위원회 의사록(2022년도 제17차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['국제/NNG;금융시장/NNG;변동성/NNG;확대/NNG', '경기/NNG;하방/..."
257,257,2022-09-22,금융통화위원회 의사록(2022년도 제18차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['물가/NNG;상승/NNG;압력/NNG;금리/NNG;상승/NNG', '가계/NNG..."
258,258,2022-10-12,금융통화위원회 의사록(2022년도 제19차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '물가/..."
259,259,2022-10-27,금융통화위원회 의사록(2022년도 제20차),\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,"['회사채/NNG;스프레드/NNG;상승/NNG', '고유동성/NNG;자산/NNG;확..."

In [8]:
del df['Unnamed: 0']

In [10]:
del df['title']

In [9]:
del df['content']

In [11]:
df

           date                                              ngram
0    2009-11-12  ['금리/NNG;인상/NNG;내외/NNG;금리갭/NNG;확대/NNG', '지표/NN...
1    2009-11-26                                  ['물가/NNG;안정/NNG']
2    2009-12-10  ['자산/NNG;가격/NNG;상승/NNG;인플레이션/NNG;압력/NNG', '원유/...
3    2009-12-24                                                 []
4    2010-01-07                                                 []
..          ...                                                ...
255  2022-08-25  ['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '국제/...
256  2022-09-08  ['국제/NNG;금융시장/NNG;변동성/NNG;확대/NNG', '경기/NNG;하방/...
257  2022-09-22  ['물가/NNG;상승/NNG;압력/NNG;금리/NNG;상승/NNG', '가계/NNG...
258  2022-10-12  ['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '물가/...
259  2022-10-27  ['회사채/NNG;스프레드/NNG;상승/NNG', '고유동성/NNG;자산/NNG;확...

[260 rows x 2 columns]

## 콜금리와 데이터들 병합

In [12]:
call = pd.read_csv('../data/callrate_preprocessing.csv')
df.date = pd.to_datetime(df.date)
call.date = pd.to_datetime(call.date)
call

           date  Unnamed: 0  callrate  month_date  month_rate label
0    2012-01-01           2      3.29  2011-12-01        0.00    up
1    2012-01-02           3      3.25  2011-12-02        0.00    up
2    2012-01-03           4      3.25  2011-12-03        0.00    up
3    2012-01-04           5      3.24  2011-12-04        0.00    up
4    2012-01-05           6      3.25  2011-12-05        0.00    up
...         ...         ...       ...         ...         ...   ...
3970 2022-11-14        3972      3.07  2022-10-14        3.07  same
3971 2022-11-15        3973      3.03  2022-10-15        3.07  down
3972 2022-11-16        3974      3.03  2022-10-16        3.07  down
3973 2022-11-17        3975      3.02  2022-10-17        3.05  down
3974 2022-11-18        3976      3.02  2022-10-18        3.08  down

[3975 rows x 6 columns]

In [13]:
del call['Unnamed: 0']

In [14]:
call

           date  callrate  month_date  month_rate label
0    2012-01-01      3.29  2011-12-01        0.00    up
1    2012-01-02      3.25  2011-12-02        0.00    up
2    2012-01-03      3.25  2011-12-03        0.00    up
3    2012-01-04      3.24  2011-12-04        0.00    up
4    2012-01-05      3.25  2011-12-05        0.00    up
...         ...       ...         ...         ...   ...
3970 2022-11-14      3.07  2022-10-14        3.07  same
3971 2022-11-15      3.03  2022-10-15        3.07  down
3972 2022-11-16      3.03  2022-10-16        3.07  down
3973 2022-11-17      3.02  2022-10-17        3.05  down
3974 2022-11-18      3.02  2022-10-18        3.08  down

[3975 rows x 5 columns]

In [15]:
df_callrate = pd.merge(df, call[['date','label']], on='date')
df_callrate

          date                                              ngram label
0   2012-01-13  ['주택담보대출/NNG;모기지/NNG;양도/NNG;포함/NNG;증가/NNG', '인...    up
1   2012-01-26                                                 []    up
2   2012-02-09  ['인플레이션/NNG;기대/NNG;지역/NNG;지정학/NNG;위험/NNG', '해외...  same
3   2012-03-08  ['농산물/NNG;제외/NNG;근원/NNG;인플레이션/NNG;하락/NNG', '인플...  down
4   2012-03-22  ['인플레이션/NNG;기대/NNG;지역/NNG;지정학/NNG;위험/NNG', '지정...  same
..         ...                                                ...   ...
207 2022-08-25  ['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '국제/...    up
208 2022-09-08  ['국제/NNG;금융시장/NNG;변동성/NNG;확대/NNG', '경기/NNG;하방/...    up
209 2022-09-22  ['물가/NNG;상승/NNG;압력/NNG;금리/NNG;상승/NNG', '가계/NNG...    up
210 2022-10-12  ['통화정책/NNG;방향/NNG;결정시/NNG;금리/NNG;상향/NNG', '물가/...    up
211 2022-10-27  ['회사채/NNG;스프레드/NNG;상승/NNG', '고유동성/NNG;자산/NNG;확...    up

[212 rows x 3 columns]

In [26]:
df_callrate.rename(columns={'article':'content'})

,date,content,ngram,label
0,2022-11-18,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,전세계적인 금리 인상과 불확실...","['금리/NNG;인상/NNG;불확실성/NNG', 'm&a/NNG;시장/NNG;위축/...",down
1,2022-11-18,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,한동안 부진을 겪었던 현대캐피...","['금리/NNG;상승/NNG;이자비용/NNG;증가/NNG', '건전성/NNG;지표/...",down
2,2022-11-18,"\r\n\r\n\t\t\t\t\t\t\t,\r\n\r\n\t\t\t\t\t\t\t\...","['자본비율/NNG;양호/NNG', '자본비율/NNG;하락/NNG', '자본비율/N...",down
3,2022-11-18,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,한화투자증권이 3분기에도 영업...","['영업이익/NNG;순이익/NNG;감소/NNG', '영업이익/NNG;감소/NNG',...",down
4,2022-11-18,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,한화에너지가 KDB산업은행의 ...","['유동성/NNG;부족/NNG;해소/NNG', '발행/NNG;여건/NNG;악화/NN...",down
...,...,...,...,...
20089,2012-01-11,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,금융감독 당국이 보험회사의 대...","['가계/NNG;부채/NNG;연착륙/NNG', '가계/NNG;부채/NNG;억제/NN...",up
20090,2012-01-11,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,한국토지주택공사(LH)가 발행...",['글로벌/NNG;경기/NNG;불황/NNG'],up
20091,2012-01-11,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,대우건설이 임차해 사용하고 있...",['자금/NNG;확보/NNG'],up
20092,2012-01-11,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,동국제강(A+, 안정적)의 차...","['원재료/NNG;가격/NNG;상승/NNG', '차입/NNG;재무/NNG;부담/NN...",up
20093,2012-01-11,"\r\n\r\n\t\t\t\t\t\t\t\t,\r\n,대우인터내셔널의 운전자본(매출...","['매출채권/NNG;증가/NNG', '운전자본/NNG;증가/NNG', '현금/NNG...",up

In [18]:
df_callrate.to_csv('../data/all_data_label_merge.csv')